language: scala

jdk:
  - openjdk11

scala:
  - 2.13.3

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_install:
  - git fetch --tags

stages:
  - name: build
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: build
      script: sbt ++$TRAVIS_SCALA_VERSION build
    - stage: release
      script: sbt ci-release
